---
kind: pipeline
type: docker
name: 3_Steps_Build

steps:

- name: 1_PreCheck_scripts
  image: alpine
  commands:
  - echo Checking if I am anonymous or any operations
  - cat /etc/*-release
  - whoami

- name: 2_Build_The_Code
  image: alpine
  commands:
  - echo A Build Simulation
  - echo DONE

- name: 3_Send_SMS
  image: curlimages/curl
  commands:
  - echo waiting the SMS server to start
  - sleep 15
  - curl http://Gateway_SMS_server:3000/outbound

services:
- name: Gateway_SMS_server
  image: ecointet/sms-server:0.3
  environment:
    DEST:
      from_secret: PHONE_NUMBER
    MESSAGE: "Hello, this is a message in your SMS service"